### ISSUE TITLE
[Feature] Github deploy action

### ISSUE THREAD

**Issue by thmsndk** [adventureland-community/al-data-explorer#5]
I would like for us to have two branches `main` and `dev`.
- An action should trigger once we make a release / push code to `main` 
- The code present in main is also what is present on the github pages / public url of aldata.

**Comment by kevinsandow** [comment]
Is this one done @Telokis ?

**Comment by Telokis** [comment]
Done in 7ecc530eeaa8c7a1628d34c29827187631a8030c
