### ISSUE TITLE
[Feature] Calculate set stats bonuses

### ISSUE THREAD

**Issue by Telokis** [adventureland-community/al-data-explorer#6]
**Is your feature request related to a problem? Please describe.**
We are currently not taking set stats into account.

**Describe the solution you'd like**
Take it into account!

**Describe alternatives you've considered**
Mental maths.

**Additional context**
![image](https://user-images.githubusercontent.com/6382729/203961318-e719c039-df6b-4613-a2e3-e284c079a0ba.png)

**Comment by thmsndk** [comment]
![image](https://user-images.githubusercontent.com/9084377/204059405-d7c1e5b0-7f93-459d-b01c-099bb7672536.png)
